name: cupertino_onboarding
description: Flutter package that provides an iOS-style onboarding experience.
version: 1.1.0
repository: https://github.com/ivirtex/cupertino_onboarding

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dots_indicator: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  dart_code_metrics: ^4.16.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  very_good_analysis: ^3.0.1
